### PR TITLE
Extended formatOnSave feature

### PR DESCRIPTION
**Pull request by hopsor**
Hi @rgreenjr,

Congrats for the awesome package you've been working on. It's definitely becoming a must in my atom editor.

Elixir code format combined with "format on save" feature is something I'm very excited after a long time using it on Elm. I'm going to use it by default in all my new projects. However there are a few existing ones which I don't want to format at all. Mainly work projects, there we'll might adopt code formatting later. 

Last week while I was switching between different Elixir projects —personal and work ones— I had to turn off/on the "format on save" functionality from the settings panel which is a little bit of a hassle.

As a solution for that problem I made this PR which extends the "format on save" feature by giving you the option of formatting all elixir projects or just the ones that includes a `.formatter.exs` file.

I hope this is something worth considering for the package. To me it's really helpful.

Cheers.

### CODE REVIEW

**Comment by rgreenjr** [comment]
Hi @hopsor – I really like this idea. I think it could be useful to many people. 

I'm in the middle of refactoring config settings right now and will pull in your changes. Thanks!

**Comment by rgreenjr** [comment]
Hi @hopsor – I just pushed the changes to the `master` branch on GitHub. Please try it out and let me know if you run into any issues. I will publish a new version with the changes hopefully soon.

**Comment by hopsor** [comment]
great! glad you like it. I'm gonna update my branch in a moment.

**Comment by hopsor** [comment]
ah, just realized you already added the changes yourself to master.

Looks good to me 👍

**Comment by rgreenjr** [comment]
I've pushed v0.4.0 live with the changes. Please let me know if you have any problems. 

Thanks for the pull request. 👍

**Pull request closed without merging**
